export const tableData = [
  {
    heading: "Department",
    data: [
      "Cardiology",
      "Dental",
      "Dermatology",
      "Neurology",
      "Nehphrology",
      "Orthopedics",
      "Oncology",
      "Ophthalmology",
      "Pediatric",
      "Ophthalmology",
      "Pediatric",
      "Physiotherapy",
      "Surgery",
      "Urology",
      "Vaccination",
      "Cardiology",
      "Dental",
      "Physiotherapy",
      "Surgery",
      "Urology",
      "Vaccination",
      "Cardiology",
      "Dental",
    ],
  },
  {
    heading: "Floor",
    data: [
      "first",
      "Second",
      "first",
      "fifth",
      "third",
      "third",
      "third",
      "Second",
      "Second",
      "first",
      "third",
      "fifth",
      "Second",
      "third",
      "Second",
      "Second",
      "first",
      "third",
      "fifth",
      "Second",
      "third",
      "fifth",
      "Second",
    ],
  },
  {
    heading: "Room",
    data: [
      203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 203, 204, 205, 206,
      203, 204, 205, 206, 207, 208, 209, 210,
    ],
  },
  {
    heading: "Token",
    data: [
      34, 32, 565, 77, 56, 89, 89, 34, 32, 565, 77, 56, 89, 567, 89, 34, 32,
      565, 77, 56, 89, 567, 89,
    ],
  },
];
